-- Estimate table size using SYSCAT.TABLES and SYSCAT.INDEXES
-- Assumes 4KB pages. If your system uses a different page size, adjust accordingly.
SELECT
'01' AS FEATURE_ID,
'Estimated Total tables and index Size (KB)' AS FEATURE_NAME,
VARCHAR(INT(SUM(DATA_OBJECT_P_SIZE + INDEX_OBJECT_P_SIZE + LONG_OBJECT_P_SIZE) * 4 / 1024)) AS VALUE
FROM
SYSIBMADM.ADMINTABINFO
WHERE
TABSCHEMA NOT LIKE 'SYS%'

UNION ALL

SELECT '02' AS FEATURE_ID,
 'Database Version' AS FEATURE_NAME,
	SERVICE_LEVEL AS VALUE
FROM SYSIBMADM.ENV_INST_INFO

UNION ALL

SELECT
'03' AS FEATURE_ID,
'Currently Connected Database Name' AS FEATURE_NAME,
VARCHAR(CURRENT SERVER) AS VALUE
FROM
SYSIBM.SYSDUMMY1



UNION ALL

SELECT '05' AS FEATURE_ID,'Materialized Query Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE TYPE IN ('M')

UNION ALL


SELECT '05' AS FEATURE_ID,'Global Temporary Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE TYPE IN ('G')

UNION ALL

SELECT
'06' AS FEATURE_ID,
'Tablespaces' AS FEATURE_NAME,
VARCHAR(COUNT(*)) AS VALUE
FROM
SYSCAT.TABLESPACES


UNION ALL


SELECT '07' AS FEATURE_ID, 'Data Types (list all unique data types)' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM ( SELECT DISTINCT COLTYPE FROM SYSIBM.SYSCOLUMNS)

UNION ALL

SELECT
'08' AS FEATURE_ID,
'Partitioned Tables' AS FEATURE_NAME,
VARCHAR(COUNT(*)) AS VALUE
FROM
SYSCAT.TABLES
WHERE
TABLEORG = 'P'

UNION ALL

SELECT '09' AS FEATURE_ID, 'Check Constraints' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSCHECKS

UNION ALL

SELECT '10' AS FEATURE_ID, 'Unique Constraints' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABCONST

UNION ALL

SELECT '11' AS FEATURE_ID, 'Replication Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM
(
SELECT DISTINCT CREATOR
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'ASN'
)


UNION ALL

SELECT '12' AS FEATURE_ID, 'Clone Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE TYPE = 'C'


UNION ALL

SELECT '13' AS FEATURE_ID, 'Auxiliary Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE TYPE = 'X'

UNION ALL

SELECT '14' AS FEATURE_ID,'Unique indexes' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSINDEXES
WHERE UNIQUERULE = 'N'

UNION ALL


SELECT '15' AS FEATURE_ID,'RowId Indexes' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSINDEXES
WHERE UNIQUERULE = 'G'

UNION ALL

SELECT '16' AS FEATURE_ID,'Database Auditing' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSAUDITPOLICIES
