-- Estimate table size using SYSCAT.TABLES and SYSCAT.INDEXES
-- Assumes 4KB pages. If your system uses a different page size, adjust accordingly.
SELECT
'01' AS FEATURE_ID,
'Estimated Total tables and index Size (KB)' AS FEATURE_NAME,
VARCHAR(INT(SUM(DATA_OBJECT_P_SIZE + INDEX_OBJECT_P_SIZE + LONG_OBJECT_P_SIZE) * 4 / 1024)) AS VALUE
FROM
SYSIBMADM.ADMINTABINFO
WHERE
TABSCHEMA NOT LIKE 'SYS%'

UNION ALL

SELECT '02' AS FEATURE_ID,
 'Database Version' AS FEATURE_NAME,
	SERVICE_LEVEL AS VALUE
FROM SYSIBMADM.ENV_INST_INFO

UNION ALL

SELECT
'03' AS FEATURE_ID,
'Currently Connected Database Name' AS FEATURE_NAME,
VARCHAR(CURRENT SERVER) AS VALUE
FROM
SYSIBM.SYSDUMMY1

UNION ALL

SELECT
'04' AS FEATURE_ID,
'Packages' AS FEATURE_NAME,
VARCHAR(COUNT(*)) AS VALUE
FROM
SYSCAT.PACKAGES
WHERE VALID = 'Y'

UNION ALL

SELECT
'05' AS FEATURE_ID,
'Base Tables (No views, No Materialized query tables, No Global temporary tables)' AS FEATURE_NAME,
VARCHAR(COUNT(*)) AS VALUE
FROM
SYSCAT.TABLES
WHERE
TYPE NOT IN ('M','V','G')

UNION ALL

SELECT
'06' AS FEATURE_ID,
'Views, Materialized query tables and Global temporary tables)' AS FEATURE_NAME,
VARCHAR(COUNT(*)) AS VALUE
FROM
SYSCAT.TABLES
WHERE
TYPE IN ('M','V','G')


UNION ALL
-- FEATURE 7 (VIEW_COUNT)
SELECT '07' AS FEATURE_ID,'Views' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE TYPE IN ('V')

UNION ALL

-- FEATURE 8 (MQT_COUNT)
SELECT '08' AS FEATURE_ID,'Materialized Query Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE TYPE IN ('M')

UNION ALL

-- FEATURE 9 (GTT_COUNT)
SELECT '09' AS FEATURE_ID,'Global Temporary Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE TYPE IN ('G')

UNION ALL


-- FEATURE 10 (TRIGGER_COUNT)
SELECT '10' AS FEATURE_ID,'Triggers' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTRIGGERS
WHERE TRIGTIME NOT IN ('I')

UNION ALL

-- FEATURE 11 (INDEX_COUNT)
SELECT '11' AS FEATURE_ID,'Indexes' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSINDEXES

UNION ALL


-- FEATURE 12 (TABLESPACE_COUNT)
SELECT
'12' AS FEATURE_ID,
'Tablespaces' AS FEATURE_NAME,
VARCHAR(COUNT(*)) AS VALUE
FROM
SYSCAT.TABLESPACES

UNION ALL

-- FEATURE 13 (SEQUENCE_COUNT)
SELECT '13' AS FEATURE_ID, 'Sequences' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSSEQUENCES

UNION ALL

SELECT '14' AS FEATURE_ID, 'Admin Authorities' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSUSERAUTH

UNION ALL


-- FEATURE 15 (DATATYPES_COUNT)
SELECT '15' AS FEATURE_ID, 'Data Types (list all unique data types)' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM ( SELECT DISTINCT COLTYPE FROM SYSIBM.SYSCOLUMNS)

UNION ALL

SELECT
'16' AS FEATURE_ID,
'Partitioned Tables' AS FEATURE_NAME,
VARCHAR(COUNT(*)) AS VALUE
FROM
SYSCAT.TABLES
WHERE
TABLEORG = 'P'

UNION ALL

SELECT '17' AS FEATURE_ID, 'Stored Procedures' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSROUTINES
WHERE ROUTINETYPE = 'P'

UNION ALL



-- FEATURE 18 (UDF_COUNT)
SELECT '18' AS FEATURE_ID, 'User-Defined Functions' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSROUTINES
WHERE ROUTINETYPE = 'F'

UNION ALL


-- FEATURE 19 (TEMPORAL_COUNT)
SELECT '19' AS FEATURE_ID, 'Temporal Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES A
WHERE A.TYPE = 'H'

UNION ALL

-- FEATURE 20 (CHECK_CONSTRAINT_COUNT)
SELECT '20' AS FEATURE_ID, 'Check Constraints' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSCHECKS

UNION ALL

-- FEATURE 21 (UNIQUE_PRIMARYKEY_COUNT)
SELECT '21' AS FEATURE_ID, 'Unique Constraints' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABCONST

UNION ALL

SELECT '22' AS FEATURE_ID, 'Replication Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM
(
SELECT DISTINCT CREATOR
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'ASN'
)

UNION ALL

SELECT '23' AS FEATURE_ID, 'Aliases' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE TYPE = 'A'

UNION ALL

SELECT '24' AS FEATURE_ID, 'Clone Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE TYPE = 'C'

UNION ALL

-- FEATURE 25 (XML_TABLE_COUNT)
SELECT '25' AS FEATURE_ID, 'XML Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE TYPE = 'P'

UNION ALL

-- FEATURE 26 (AUXILARY_TABLE_COUNT)
SELECT '26' AS FEATURE_ID, 'Auxiliary Tables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE TYPE = 'X'

UNION ALL

-- FEATURE 27 (WHERE_NOT_NULL_INDEXES_COUNT)
SELECT '27' AS FEATURE_ID,'Unique indexes' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSINDEXES
WHERE UNIQUERULE = 'N'

UNION ALL



-- FEATURE 28 (ROWID_INDEXES_COUNT)
SELECT '28' AS FEATURE_ID,'RowId Indexes' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSINDEXES
WHERE UNIQUERULE = 'G'

UNION ALL

-- FEATURE 29 (AUDIT_POLICIES_COUNT)
SELECT '29' AS FEATURE_ID,'Database Auditing' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSAUDITPOLICIES


UNION ALL

-- FEATURE 30 (GLOBAL_VARIABLES_COUNT)
SELECT '30' AS FEATURE_ID,'Global Variables' AS FEATURE_NAME, VARCHAR(COUNT(*)) AS VALUE
FROM SYSIBM.SYSVARIABLES
