-- Define your schema name
WITH SCHEMA_CONTEXT (USER_SCHEMA) AS (
  SELECT '<YOUR_SCHEMA>' FROM SYSIBM.SYSDUMMY1
)

-- Unified metadata query
SELECT * FROM (
  -- PACKAGES
  SELECT
    'PACKAGE' AS FEATURE_NAME,
    PKGSCHEMA AS SCHEMA,
    PKGNAME AS NAME,
    CAST(NULL AS CLOB) AS TABLE_NAME,
    CAST(NULL AS CLOB) AS EVENT,
    OWNER,
    CREATE_TIME,
    ALTER_TIME,
    CAST(NULL AS CLOB) AS DEFINITION,
    CAST(NULL AS INTEGER) AS LINE_COUNT,
    CAST(NULL AS CLOB) AS COLUMN_NAMES,
    CAST(NULL AS CLOB) AS INDEX_TYPE
  FROM SYSCAT.PACKAGES, SCHEMA_CONTEXT
  WHERE VALID = 'Y' AND PKGSCHEMA = USER_SCHEMA

  UNION ALL

  -- VIEWS
  SELECT
    'VIEW' AS FEATURE_NAME,
    VIEWSCHEMA AS SCHEMA,
    VIEWNAME AS NAME,
    CAST(NULL AS CLOB) AS TABLE_NAME,
    CAST(NULL AS CLOB) AS EVENT,
    OWNER,
    CAST(NULL AS TIMESTAMP) AS CREATE_TIME,
    CAST(NULL AS TIMESTAMP) AS ALTER_TIME,
    TEXT AS DEFINITION,
    LENGTH(TEXT) - LENGTH(REPLACE(TEXT, CHR(10), '')) + 1 AS LINE_COUNT,
    CAST(NULL AS CLOB) AS COLUMN_NAMES,
    CAST(NULL AS CLOB) AS INDEX_TYPE
  FROM SYSCAT.VIEWS, SCHEMA_CONTEXT
  WHERE VIEWSCHEMA = USER_SCHEMA

  UNION ALL

  -- TRIGGERS
  SELECT
    'TRIGGER' AS FEATURE_NAME,
    TRIGSCHEMA AS SCHEMA,
    TRIGNAME AS NAME,
    TABNAME AS TABLE_NAME,
    TRIGEVENT AS EVENT,
    OWNER,
    CAST(NULL AS TIMESTAMP) AS CREATE_TIME,
    CAST(NULL AS TIMESTAMP) AS ALTER_TIME,
    TEXT AS DEFINITION,
    LENGTH(TEXT) - LENGTH(REPLACE(TEXT, CHR(10), '')) + 1 AS LINE_COUNT,
    CAST(NULL AS CLOB) AS COLUMN_NAMES,
    CAST(NULL AS CLOB) AS INDEX_TYPE
  FROM SYSCAT.TRIGGERS, SCHEMA_CONTEXT
  WHERE TRIGSCHEMA = USER_SCHEMA

  UNION ALL

  -- INDEXES
  SELECT
    'INDEX' AS FEATURE_NAME,
    INDSCHEMA AS SCHEMA,
    INDNAME AS NAME,
    TABNAME AS TABLE_NAME,
    CAST(NULL AS CLOB) AS EVENT,
    OWNER,
    CREATE_TIME,
    CAST(NULL AS TIMESTAMP) AS ALTER_TIME,
    CAST(NULL AS CLOB) AS DEFINITION,
    CAST(NULL AS INTEGER) AS LINE_COUNT,
    COLNAMES AS COLUMN_NAMES,
    INDEXTYPE AS INDEX_TYPE
  FROM SYSCAT.INDEXES, SCHEMA_CONTEXT
  WHERE INDSCHEMA = USER_SCHEMA

  UNION ALL

  -- SEQUENCES
  SELECT
    'SEQUENCE' AS FEATURE_NAME,
    SEQSCHEMA AS SCHEMA,
    SEQNAME AS NAME,
    CAST(NULL AS CLOB) AS TABLE_NAME,
    CAST(NULL AS CLOB) AS EVENT,
    CAST(NULL AS VARCHAR(128)) AS OWNER,
    CAST(NULL AS TIMESTAMP) AS CREATE_TIME,
    CAST(NULL AS TIMESTAMP) AS ALTER_TIME,
    CAST('START: ' || CHAR(START) || ', INCREMENT: ' || CHAR(INCREMENT) ||
         ', MIN: ' || CHAR(MINVALUE) || ', MAX: ' || CHAR(MAXVALUE) AS CLOB) AS DEFINITION,
    CAST(NULL AS INTEGER) AS LINE_COUNT,
    CAST(NULL AS CLOB) AS COLUMN_NAMES,
    CAST(NULL AS CLOB) AS INDEX_TYPE
  FROM SYSCAT.SEQUENCES, SCHEMA_CONTEXT
  WHERE SEQSCHEMA = USER_SCHEMA

  UNION ALL

  -- PROCEDURES
  SELECT
    'PROCEDURE' AS FEATURE_NAME,
    ROUTINESCHEMA AS SCHEMA,
    ROUTINENAME AS NAME,
    CAST(NULL AS CLOB) AS TABLE_NAME,
    CAST(NULL AS CLOB) AS EVENT,
    CAST(NULL AS VARCHAR(128)) AS OWNER,
    CAST(NULL AS TIMESTAMP) AS CREATE_TIME,
    CAST(NULL AS TIMESTAMP) AS ALTER_TIME,
    TEXT AS DEFINITION,
    LENGTH(TEXT) - LENGTH(REPLACE(TEXT, CHR(10), '')) + 1 AS LINE_COUNT,
    CAST(NULL AS CLOB) AS COLUMN_NAMES,
    CAST(NULL AS CLOB) AS INDEX_TYPE
  FROM SYSCAT.ROUTINES, SCHEMA_CONTEXT
  WHERE ROUTINESCHEMA = USER_SCHEMA AND ROUTINETYPE = 'P'

  UNION ALL

  -- FUNCTIONS
  SELECT
    'FUNCTION' AS FEATURE_NAME,
    ROUTINESCHEMA AS SCHEMA,
    ROUTINENAME AS NAME,
    CAST(NULL AS CLOB) AS TABLE_NAME,
    CAST(NULL AS CLOB) AS EVENT,
    CAST(NULL AS VARCHAR(128)) AS OWNER,
    CAST(NULL AS TIMESTAMP) AS CREATE_TIME,
    CAST(NULL AS TIMESTAMP) AS ALTER_TIME,
    TEXT AS DEFINITION,
    LENGTH(TEXT) - LENGTH(REPLACE(TEXT, CHR(10), '')) + 1 AS LINE_COUNT,
    CAST(NULL AS CLOB) AS COLUMN_NAMES,
    CAST(NULL AS CLOB) AS INDEX_TYPE
  FROM SYSCAT.ROUTINES, SCHEMA_CONTEXT
  WHERE ROUTINESCHEMA = USER_SCHEMA AND ROUTINETYPE = 'F'

  UNION ALL

  -- SENSITIVE COLUMNS
  SELECT
    'SENSITIVE COLUMN' AS FEATURE_NAME,
    TABSCHEMA AS SCHEMA,
    TABNAME AS NAME,
    CAST(NULL AS CLOB) AS TABLE_NAME,
    CAST(NULL AS CLOB) AS EVENT,
    CAST(NULL AS VARCHAR(128)) AS OWNER,
    CAST(NULL AS TIMESTAMP) AS CREATE_TIME,
    CAST(NULL AS TIMESTAMP) AS ALTER_TIME,
    CAST(NULL AS CLOB) AS DEFINITION,
    CAST(NULL AS INTEGER) AS LINE_COUNT,
    COLNAME AS COLUMN_NAMES,
    CAST(TYPENAME AS CLOB) AS INDEX_TYPE
  FROM SYSCAT.COLUMNS, SCHEMA_CONTEXT
  WHERE TABSCHEMA = USER_SCHEMA
    AND (
      LOWER(COLNAME) LIKE '%name%' OR LOWER(COLNAME) LIKE '%phone%' OR LOWER(COLNAME) LIKE '%email%' OR
      LOWER(COLNAME) LIKE '%ssn%' OR LOWER(COLNAME) LIKE '%address%' OR LOWER(COLNAME) LIKE '%dob%' OR
      LOWER(COLNAME) LIKE '%birth%' OR LOWER(COLNAME) LIKE '%credit%' OR LOWER(COLNAME) LIKE '%card%' OR
      LOWER(COLNAME) LIKE '%account%' OR LOWER(COLNAME) LIKE '%password%' OR LOWER(COLNAME) LIKE '%contact%' OR
      LOWER(COLNAME) LIKE '%pwd%' OR LOWER(COLNAME) LIKE '%midinit%' OR LOWER(COLNAME) LIKE '%bonus%' OR
      LOWER(COLNAME) LIKE '%salary%' OR LOWER(COLNAME) LIKE '%loca%' OR LOWER(COLNAME) LIKE '%social_security_number%'
    )

  UNION ALL

  -- XML OBJECTS
  SELECT
    'XML OBJECT' AS FEATURE_NAME,
    OBJECTSCHEMA AS SCHEMA,
    OBJECTNAME AS NAME,
    CAST(NULL AS CLOB) AS TABLE_NAME,
    CAST(NULL AS CLOB) AS EVENT,
    OWNER,
    CREATE_TIME,
    ALTER_TIME,
    CAST(NULL AS CLOB) AS DEFINITION,
    CAST(NULL AS INTEGER) AS LINE_COUNT,
    CAST(NULL AS CLOB) AS COLUMN_NAMES,
    CAST(NULL AS CLOB) AS INDEX_TYPE
  FROM SYSCAT.XSROBJECTS, SCHEMA_CONTEXT
  WHERE OBJECTSCHEMA = USER_SCHEMA

  UNION ALL

  -- USER DEFINED TYPES
  SELECT
    'USER DEFINED TYPE' AS FEATURE_NAME,
    TYPESCHEMA AS SCHEMA,
    TYPENAME AS NAME,
    CAST(NULL AS CLOB) AS TABLE_NAME,
    CAST(NULL AS CLOB) AS EVENT,
    CAST(NULL AS VARCHAR(128)) AS OWNER,
    CAST(NULL AS TIMESTAMP) AS CREATE_TIME,
    CAST(NULL AS TIMESTAMP) AS ALTER_TIME,
    CAST(NULL AS CLOB) AS DEFINITION,
    LENGTH AS LINE_COUNT,
    CAST(NULL AS CLOB) AS COLUMN_NAMES,
    CAST(NULL AS CLOB) AS INDEX_TYPE
  FROM SYSCAT.DATATYPES, SCHEMA_CONTEXT
  WHERE TYPESCHEMA = USER_SCHEMA AND OWNERTYPE = 'U'

  UNION ALL

  -- ROLES
  SELECT
    'ROLE' AS FEATURE_NAME,
    NULL AS SCHEMA,
    ROLENAME AS NAME,
    CAST(NULL AS CLOB) AS TABLE_NAME,
    CAST(NULL AS CLOB) AS EVENT,
    CAST(NULL AS VARCHAR(128)) AS OWNER,
    CAST(NULL AS TIMESTAMP) AS CREATE_TIME,
    CAST(NULL AS TIMESTAMP) AS ALTER_TIME,
    CAST(NULL AS CLOB) AS DEFINITION,
    CAST(NULL AS INTEGER) AS LINE_COUNT,
    CAST(NULL AS CLOB) AS COLUMN_NAMES,
    CAST(NULL AS CLOB) AS INDEX_TYPE
  FROM SYSCAT.ROLES
) AS FULL_METADATA
ORDER BY CREATE_TIME DESC;
